### ISSUE TITLE
graph components analysis

### ISSUE THREAD

**Issue by shriv** [rowinf/data-hack2021#2]
Run components algorithm on (keywords) graph and associate component label to node data. Depends on #1

**Comment by shriv** [comment]
## Notes
- I split out the keywords column and created a basic keyword co-occurrence dataset
- Had to filter out "New Zealand" and "roads" as they were quite prolific and generic. Probably need to filter out more generic ones..! 
- Created a graph data structure with `tidygraph`. 
- For tidy visualisations, I had filter out only those key-word pairs with more than 2 papers linking them. 
- I have a very basic component ("community") analysis. There are a bunch of algos we can choose from I think. I used [this one](https://rdrr.io/cran/igraph/man/cluster_infomap.html) but need to really understand the meaning.. 
![image](https://user-images.githubusercontent.com/3827179/145749215-fa8ff08c-5931-4d25-a092-c6b92035368e.png)

**Comment by Waterman3** [comment]
Good morning everyone,

I think I have a conceptual idea of how this works. I think the  choice of
the algorithm  is a good one as the paper gives scientific papers as an
example.

The algorithm can produce a graph of topics based on how closely-related
they are.  How do we then attach the papers?

Regards,
Warwick

**Comment by shriv** [comment]
Cheers @Waterman3 ! :-) 
I'll look up community detection / graph component algorithms today to see if there is a particular implementation that is more akin to a topic identification. It's a good point about _how_ we attach the papers usefully? We could add the papers as attributes to the nodes but we will have double-ups. One possible route forward is associating papers with the communities? Click on a community and it will give you a list of all papers belonging to it. So, we attribute the papers to an element outside of the graph's node / edge attributes. I will create an issue for us to think through different graph data models that will better connect to papers and also ultimately, get to the kumu model. 

I also had this idea that once we have "communities" ("topics"), we can find keywords that connect more than one topic i.e. lynchpin nodes. These keywords could be a useful point for discovering more loosely connected literature.

**Comment by shriv** [comment]
## Notes (15/12/21)
- Final analysis in this issue is that of a "papers network" - where papers are connected by shared keywords. There was consensus that this is a good graph data model making #4 unnecessary. I will close #4. 
- Still need to figure out the better / best clustering algorithm.
